services:
  api:
    build:
      context: .
      dockerfile: BarbershopBookApi.WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS = 5000
      - ASPNETCORE_HTTPS_PORTS = 5001
      - ConnectionStrings__Postgres=Host=db;Port=5432;Database=BarbershopBook;Username=postgres;Password=1234;
      - Jwt__Token=asdandiawuhqoije19823y1279823eyqwjdnqasjkdbyqw34y1i3q09ei19ejadnaosdwqe12938!!*&Y!*&@jwediqwdtertet43525235@!@E!3213wqeq
      - Jwt__Issuer=https://localhost:5001
      - Jwt__Audience=https://localhost:5001
    volumes:
      - C:\Users\Магжан\AppData\Roaming\Microsoft\UserSecrets\7f775d89-bcdc-4b4f-8e62-263fc2ed1407
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: BarbershopBook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: